# FIXME: web 관련 dependency compile time 에 제외해야함
spring:
  main:
    web-application-type: none

ygtang:
  slack:
    token:
      bot: ENC(/vYHx8EfqXQ5Q+wUpBxmEkde8Nz0i32a1I1uFPzi7X5bOsfQ1/BU7/enM9DMzHt2VO7FwgOELpKfAkjc98kzHG4stHPZKF3mJ5Xqf0p9SeAEyMvv+Y6JPZojjQ755zAT)