version: "3.9"
services:
  app:
    image: "${IMAGE_REPO_NAME}:${IMAGE_TAG}"
    container_name: ${ACTIVE}
    ports:
      - "8080:8080"
      - "8081:8081"
      - "5005:5005"
    volumes:
      - "${YGTANG_LOG_DIR}:/logs"
    environment:
      - "JAVA_OPTS=${JAVA_OPTS}"
