version: "3.9"
services:
  app:
    image: "${IMAGE_REPO_NAME}:${IMAGE_TAG}"
    container_name: ${ACTIVE}
    ports:
      - "8080:8080"
      - "8081:8081"
      - "5005:5005"
    volumes:
      - "${YGTANG_LOG_DIR}:/logs"
    environment:
      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005 -Dspring.profiles.active=${ACTIVE} -Duser.timezone=Asia/Seoul -Djasypt.encryptor.password=${ENC_PASSWORD} -Dserver.tomcat.accesslog.enabled=true -Dserver.tomcat.basedir=/ -Dlogging.level.org.apache.catalina.core=OFF -Dlogging.file.name=/logs/spring.log"
