spring:
  jwt:
    secret: ${SECRET_KEY}
  cache:
    type: redis

cloud:
  aws:
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    region:
      static: ${S3_REGION}
    s3:
      bucket: ${S3_BUCKET}
    stack:
      auto: false

slack:
  token: xoxb-3237426898912-3687228249525-kDMMRxpwu5FGEELfZy3f5Z73
  channel:
    monitor: C037Q0JV19B