spring:
  flyway:
    enabled: true
  mail:
    sign-up-email-send-mail: ENC(zyANvPjCAYiH+b6CSKvf0B3vMD1eU7NaOfqeUWVs2Mj4eCMvDa7Y6qpAV5h02jbihEC/I6zmjIZqsPu1VTdUadTTuVPVcLyqTJGlRYS5rLlEcXGhZ4zg+Nu8+3S8otsn)
    reset-password-for-auth-send-mail: ENC(TtTKtnwv64ttIONkMuT1SF6r/iU2NWV+hI17DTupgugbuj50RsiIsEXowUUmFoVz7fh01FBNkq0dKhkaDEK+BLWtRchs9Z+koSAMSNqvGhby2+8rHzRfIL3FMTzEGeHt)

cloud:
  aws:
    credentials:
      access-key: ENC(TytE6PoRN2G8XiwPq3IU+4GFVHPcNmWXUkYk2MApOEY2a6IZZg0pjew8eXWoa6aWmbUfk/xWWapJee+bucL5Qg==)
      secret-key: ENC(VvzJa/x/ByNQuonkVRPTWD5zK0EA0YwCBtwhwytxgezkOe95PE6UYMObHiRsKNEmLiH9iIuh1b16M6vy1K3uvSXSa9supz8GR+Kkuz2we5E=)
    s3:
      bucket: ENC(PuGrKff6b61oLzn8MOMis/s+ddimZXme4J8HTemFL4seX6C0y4n44vdXRO2PvcLq0W4nx7cX0Jq7a5ZfQWms6g==)

logging:
  file:
    name: spring.log


ygtang:
  domain:
    datasource:
      jdbcUrl: ENC(2TUXqdayoRK4iQZ+oI04Nhpy85dCeOUIq8G/Zw/fBwi+DsAwfOBHB/rsz/2k3Or67tSp+cHil1YkOmzkGzmfgZDktSEjBK4GVJk0Z3ScwLu55RWXCEfsbD5xVaITkFl9nWa8PpGyzb5fHfDT/8ueZn7Z9e6VaF77xE4QIorrFIsOQcM+mPDfLYUOYZk+GhJguxerA/b887kiWjph+JOlbmvMScn55gwfpXZMEVyX5HDoWqHgtD+ahzfCaEyyhsa13K9xtHlPaIAcV1vgUUAcr5p2pG/zIbTUY1WfeV4yr1hNQqd0MfoCUhGdfMYMDYWHbZ5Hpv9WZFWchWUSuCHiwQ==)
      username: ENC(jZEdjhanW1BDicsE9g4W205D8n3mIXUiVUchGBakPhNNKx2BB6Ig2SczCQ7P0P3M)
      password: ENC(wHtJt3OkgAgOD8+3nc1BBuVswm2VozoyOxXBjrANQp69+Jd0ugUSXkO5LkbocVtQ)
      driver-class-name: com.mysql.cj.jdbc.Driver

uri:
  webhook: ENC(d6rn2vUIq/fnrv6k5m9EhuVtKxJGXm6Qf5NPGgaPMHa1yBld8nFPwxTh/XX9iVqweVSvnLXj0RNYQ9vNsoOiR1YtfqQi7jBFDtGYT7T8KEHZ6FVnwx499LoHKHAZBKF4GoX1kawUV7iPP+tSr5UvNkZkjGEYUqBzqmVgXvTXZng=)
