spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    url: ENC(LrkgijSkKkCUclnsz2iCawvdG+h5A8iI4+6znCPrkjeJ4cidFO1cMwdHdUx2ZMgEJsTzJswVmz7pdspyod4FX4sY+djvhgk7s5O5+cd24dHcaJ75AcCxwh4aAdaXmtyJ2jkeAwC8709AKiUIYDD7u06gVeZSHkWTtHueEGr9IignsaHm1U+yQVxkiU1lveym1PHh3Q3yApgDsXuG5eStNYrFKSpyn3HQisw24vavAIHPQRJVZNTiwyxEv6mB0z9fc1IAAjBgVTusGw4lxli4mzSwNpHFK5wKL/NDJh1VEs67iuIRcnrgonvtFmtxlvmX0sVeMHHlJoEgLaq1k4NrPg==)
    user: ENC(pD8lmKr4PXMRCUto6pMF9Ub/iJCxKveTODoqXQm1fDEB4rVN1Nzs6sftmidgYWOP)
    password: ENC(MJISIAE2hpfyzQjAFQwM8o+Wtv5rHP5lJDwBq3mEIUkr93OEMj+uqYmXDjasb7El)
  mail:
    reset-password-for-auth-send-mail: ENC(GeC90mA3UZZDdttZYktCwjx5gl00nT+ZGOOlCmT3UuTzwgvnGBqby+LjMl1BVfJ6B0leFjbJVUbkkykNQ0i/9/f6MPYopOgJy0sCaL8QlypSmzJy5Vkq98KTbAu18nsg)

logging:
  file:
    name: spring.log

cloud:
  aws:
    credentials:
      access-key: ENC(fSugXvM7vE9xH3LO8SjlJHeDPAz3Grh9Z0soZW4YoXmtz/FP2nlFrzOw+dPd2qpQz8a7c60fKdgI/uOSJ8upzw==)
      secret-key: ENC(YiKVUKqdW6IeY+zcvhSzhb65e1rVU5MFn174HDKFBb0xinizK9EwCsdj06ZAeEh7sAuWJ/DnI/w5/gC5bE4cRjO82NRIAT9aSVG2VVsemmc=)
    s3:
      bucket: ENC(hrPVDZuG83TgagLFUG7MchbMlA30RYJJU1sW8ToTYyUguoCcZiLVgtALJwQq6JRPZzfa2/WX6k0I2o/FiTurHA==)
    ses:
      access-key: ENC(ONeXLvOC69T9yj0Z1aECuoxIpTHA4rR7JKdYMtaio7rsvTWdYOIZoZcxRGDDFcDHv8MOH5gNapl+AfWnuLdxww==)
      secret-key: ENC(5mbWA0xUqs/kKMOXT88QRvCh43GO3ECyzmXRxDcVCX/5XajI9Xvk6Mz1qW2oNc3CfC5p6GzxzjhSXmJ7muzHPon3rALCs93hYXNIJiYzUVo=)

ygtang:
  domain:
    datasource:
      jdbcUrl: ENC(LrkgijSkKkCUclnsz2iCawvdG+h5A8iI4+6znCPrkjeJ4cidFO1cMwdHdUx2ZMgEJsTzJswVmz7pdspyod4FX4sY+djvhgk7s5O5+cd24dHcaJ75AcCxwh4aAdaXmtyJ2jkeAwC8709AKiUIYDD7u06gVeZSHkWTtHueEGr9IignsaHm1U+yQVxkiU1lveym1PHh3Q3yApgDsXuG5eStNYrFKSpyn3HQisw24vavAIHPQRJVZNTiwyxEv6mB0z9fc1IAAjBgVTusGw4lxli4mzSwNpHFK5wKL/NDJh1VEs67iuIRcnrgonvtFmtxlvmX0sVeMHHlJoEgLaq1k4NrPg==)
      username: ENC(pD8lmKr4PXMRCUto6pMF9Ub/iJCxKveTODoqXQm1fDEB4rVN1Nzs6sftmidgYWOP)
      password: ENC(MJISIAE2hpfyzQjAFQwM8o+Wtv5rHP5lJDwBq3mEIUkr93OEMj+uqYmXDjasb7El)
      driver-class-name: com.mysql.cj.jdbc.Driver
  server:
    scheme: https
    host: ENC(nhcx6FgoC9f1sw8x+IXZxUeA7jVGC00faq6kqZ9qJK5ZgKS/ayDPiY+swiTOrb1e)
    port: 443

uri:
  webhook: ENC(KSZZjsE2e2j/6aQIb1EFZmIqM+S2qW2hY6/k9X97URbVEUcE6jNH60ZF186hVIpfmx3u4kZ3MgLboXvzId3CCFg3uIovOW5iiEh9T2zwf+wtK7GvcD0DaJ+H+xhRadViI5xoKD1aR6OMcVvDOwJurBVa6BFy0VemoIuSt+nQNYM=)
