spring:
  application:
    name: inspriation
  jpa:
    hibernate:
      ddl-auto: validate
    generate-ddl: false
    properties:
      hibernate:
        default_batch_fetch_size: 100
  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(uL7Og9J574ABbkuxuqqmUcSpZ5X/Lzj+JTUKL63FZ5YbDuuic0xg9+b/M+N/DECQ5Li/bbwa73NZ7hh+6wwWAw==)
    password: ENC(Q3i86abe2zQVkwIl4P/VWxGJqw4SdyJ6U8+QKUJysdsNUZiOYVToeu/Tz7oAJjIA93kZXQ/ZEVAVyaTnjOn85A==)
  jwt:
    secret: ENC(88bpwlUo++X0KVfhWI04B7hxT9Yi+2D4fuz+lmoVUD2uqtDzinqHZWkkrmoC7F+k)

cloud:
  aws:
    region:
      static: ap-northeast-2
    s3:
      connection-timeout: 1000
      request-timeout: 3000
    ses:
      access-key: ENC(DB73NBzZBXtuco5qOP1/jtb+hE69JqfkbcuiM43tPG9sWNms0P+pqFaYc3gsAauMKMtI7Uz3JyOOIqztitWLcA==)
      secret-key: ENC(2FeuLoZ4l1L33nWOSUzx0sXsDfO4b5NaVgu6EiGDnXRF+E1cgCqtI32xKsz11zzNuFVrueqJ/YyxmTO9yKXUPNs088t0G4LkyjMmHpmmZCg=)

uri:
  webhook:
