spring:
  flyway:
    url: ENC(VLJkyh7IKkXzw12UKNpUQUKFg/pk2mrkInf5nLQHUysPr7AM7NvBkKbDNus7XoLiY77mUpMhFLSiTR/uLcdBU61Wdw54Kf+aa71Cw9bQqmbo8VDTzeL8FqJyxeslbMsflgpf/v5DPq0n6CO2aLPC4sm9eQk1LWcM6Z8QmH8lsMyKI4r9aqxZN74KJxgMdXvdTgIQgvkClAMniK67xJtzIj3FayVFfGR+DpZw9jSh3XmbQLk/EluLTRF7++aio0qhHda89OWC7v+CRcp08SMx4g08e6jusanaDM45f8cOrI1LPK9pNebxNaCYbFH+Ac4vhcOlxYj746we4uGFUgwtaA==)
    user: ENC(E8406QQDMQ7ECPu2+JnNUe06yv2ToNEGBIPsi2jym2HHRmzy0G67ZAA61Vtw6vQ1)
    password: ENC(qvOCpX2nuEMvhDC/blKOGkIWtpgoZn6HokZz+aD9R51Vz8Es3wolJKooOmSbY7qA)
  mail:
    reset-password-for-auth-send-mail: ENC(IB6E6riPVm26QrSJ/UpkVeyrAFKGdT+cN7ScH3ao3z2PLI86H0qp5bO81enfchb+h05MWHEVzT5tlgtB18/LNZH7BnC3NF86pRTIydwnTVxht5ysHUdV1nDu4KaLfO6i)

cloud:
  aws:
    credentials:
      access-key: ENC(Q5OQ9RUejCYZR2qublCd3NuUL7/2gpTza9tHIpRVSdfRstWUOfM39SMXZZsWca3VM/awaA3dCevMgK6MeYt4Qw==)
      secret-key: ENC(uaF8plhwtIWsD6jOeKCjH3570Kud9+lE/PUZUMMduKGG5YlDLS+TiPnt3uWNHBif3yHJqsIa4XXAxbYwxA6tvxmq/s9D/vThv5o4UKHVA78=)
    s3:
      bucket: ENC(t+QBhlmO63TiDPPw9EkramrPUYtl026a6JwpubNd+5o3dmEQAourhDa54VL49di2/B8foPKfnHldCVFj4+hmKQ==)

logging:
  file:
    name: spring.log

ygtang:
  domain:
    datasource:
      jdbcUrl: ENC(b4whWY/yLqxBSu2GuznKG9GDOS4MGro4k+11KKG5hUj3joKCEYDakqBjsoxnPuDjVaa/LU6WW1/4t4o/nXvyIpcleHA5gZI3Dsw5q5Q4nCCTCNbXeOGWFx4EkKsoLt7B+lIWEhOgYI+UZh9sP4h2vpZ3xVC2u7OBOzGrFLSD0SIh8QFl30R1K+W7wdMosVsgPufchMPVRV5Bv2Rnm9CgwzY+IUVWDWDa0Gh2YqkfM1eMEL2ulJjr3mnGEo7I03VwZ4fnRcFQzvZCMdSXKIn07cy47Rjr1jfIuuY/ukoTpANnqTRmcMyAKfmiSty0oNY2PWuTut3MNB0XyzVjepJbIQ==)
      username: ENC(54oHO5nphKBQYZw0wmTle0U5Ge4vzJleCyAfRo1NKzvPEo2/5ConNOvFxnemd/Ka)
      password: ENC(ZQLEarZA4Wb9wP0TYUodGhqutNn+thf7hmGYd2ooEnQLQAZ33P5JnbIpAZYkm9+4)
      driver-class-name: com.mysql.cj.jdbc.Driver
  server:
    scheme: https
    host: ENC(t7KBKUqd4gxWbQ9pgu10cshwUpDyQI3M6Mzs3Pmv8h0fo9OpFYn6BP3dN57ftSFG)
    port: 443

uri:
  webhook: ENC(Lrl4SA/DSisdnZccrM1LX8cku7BUmBLs7ts/xSxWjd40niap1x0VyzF4/OT45gXEFxURWv3Cl+LsmMik49sNrD9Bxss1TOU0aNpdc4mZvoPL9yrHrqDz2XJ/qVs4Ldh3TNeBE7R/JGDIS7lKYXJfOta26+8IojirJ8QJYUDNraw=)
