spring:
  flyway:
    url: ENC(DiuH5gQbIMnSu4B1O0TC+AQrUHJGyjA+lkVRRuFmEzVVHDDlKo6fKZEJX+UibptIx415dJbnuPPLwKap1WzTNmNXvFEWcvAgoGw8WAXQoF41SbPuWxzhIDg5mg/PhvrCCtC7UCsOpel1EqcTFn+49nPZP59vIlvAqgzQCxfyYqh4dn1NF/qs2HesVCrUefPQorG/yk1LI1c5rfhnWQhjuxdWDi7fVkISxM15csTifiqTOhcziVkaWkd/QnnD3Z3YJBUTTkykJ7dUQpVluX1SNZWsKGtBNKjYtqS2T6BzbdH7m1jtyQp4XzrH+SoPrZjSPEhHCQ6XkG3JMg40ygY62Q==)
    user: ENC(pD8lmKr4PXMRCUto6pMF9Ub/iJCxKveTODoqXQm1fDEB4rVN1Nzs6sftmidgYWOP)
    password: ENC(MJISIAE2hpfyzQjAFQwM8o+Wtv5rHP5lJDwBq3mEIUkr93OEMj+uqYmXDjasb7El)
  mail:
    reset-password-for-auth-send-mail: ENC(TtTKtnwv64ttIONkMuT1SF6r/iU2NWV+hI17DTupgugbuj50RsiIsEXowUUmFoVz7fh01FBNkq0dKhkaDEK+BLWtRchs9Z+koSAMSNqvGhby2+8rHzRfIL3FMTzEGeHt)

cloud:
  aws:
    credentials:
      access-key: ENC(z604OvMg8DC1QJ7EmDy5rbaZusHJDVqNB/5QFpXEogERDROq1xQJIJYeVOrbTlf+kSFUq92HXsp9qjLArxDLjg==)
      secret-key: ENC(Ex+M59/bYV59b9OQy+ZTwHgdhsw/lzVBidiBzr5nyu8uXb6GrM1k+KfLusS0dTt38KzK8wKd9r5kvFU60ML1i5y061xyeRWunnBuvUWwXrQ=)
    s3:
      bucket: ENC(R9pmaGtILn87+LKOpZHuj7rrEMm+4zV7cUUWs08/kQyZqKI6dMKYTg6/ZpZZ2SkExhq+inG0Ar/9CUEIQmhvmQ==)
    ses:
      access-key: ENC(zx9Al4s2xHV7KK+NiRnrg/Vh0Fzf+yOySkKoK3Bnu+ub1+6qXUrZkKQEE8BsfMusAJu68GlKdB1PH3/PBoyooQ==)
      secret-key: ENC(QRM7fc2nEakhcdw0eio2Mg1rvaCT+spuF4Si7VnuQvBFg4FjB/Pm4N0euTmHK3nu+/B1PhCKdt4YXLH13yVOIOMN7awJjYYmm5t3uLDrfOY=)

logging:
  file:
    name: spring.log


ygtang:
  domain:
    datasource:
      jdbcUrl: ENC(T6KJD2K4zrrg9wj23w7I1RCcS0YBAwntd8KhtD9TonbAhXrvwkqlF98vqDfc9puBqGQU2CEAJScvfiMlig0Jz41E7gKy7k5GGbe3cTVYXiILrYo+/KBXhCtMo0qJq13wqgAn55fElbTgS4Eq9+tDV/SkRB3I5eO+2Eny6lv/j9kwz+Ko46bgch7PJmRHuQY9OFN92u1rv4y0KBYFYqUlGLHVaTDzxKtazGXcWWbV5/XYZK+A0cqX2p9EjfclXf7lfJw2fxHwiFhIWiHY6cXeqBi+1zdWJMCsYMGq3uN8jiAeR25HuF5N5nSyBPjYh5XdEJMi8E58iiDiA9MUqcE/3Q==)
      username: ENC(pD8lmKr4PXMRCUto6pMF9Ub/iJCxKveTODoqXQm1fDEB4rVN1Nzs6sftmidgYWOP)
      password: ENC(MJISIAE2hpfyzQjAFQwM8o+Wtv5rHP5lJDwBq3mEIUkr93OEMj+uqYmXDjasb7El)
      driver-class-name: com.mysql.cj.jdbc.Driver
  server:
    scheme: https
    host: ENC(cm4VELioPGIOdzRjWigLUeo7GDiwRwUK4CDjibCSt9ODl1CMwfUolW+eqeXKJ8Hj)
    port: 443

uri:
  webhook: ENC(d6rn2vUIq/fnrv6k5m9EhuVtKxJGXm6Qf5NPGgaPMHa1yBld8nFPwxTh/XX9iVqweVSvnLXj0RNYQ9vNsoOiR1YtfqQi7jBFDtGYT7T8KEHZ6FVnwx499LoHKHAZBKF4GoX1kawUV7iPP+tSr5UvNkZkjGEYUqBzqmVgXvTXZng=)
