spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080
  tomcat:
    basedir: .
    accesslog:
      enabled: true

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: "health,info"