spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080
  tomcat:
    basedir: .
    accesslog:
      enabled: true
      pattern: ENC(B9dLQKgqNIrYikP876ShuSsbo8d9NhPl0EqGt5fGh2OJ885fUKykci0Zz7/21LeueW3Cagm5SpQKVAnshSl1z/pQLGOdjq0+8SxklexAxvXQdDfdPN3noxUYvykoW1EV/+e5Ekpho0Ocf62l1f3sia0JuFFMeuAooRRhF/BKbf4=)

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: "health,info"

logging:
  level:
    org:
      apache:
        catalina:
          core: OFF
